### PR TITLE
Update MessageCard to AdaptiveCard

### PR DESCRIPTION
**Pull request by minhazur-piash**
The scope of this PR is to update legacy [MessageCard](https://learn.microsoft.com/en-us/outlook/actionable-messages/message-card-reference#section-fields) to [AdaptiveCard](https://learn.microsoft.com/en-us/outlook/actionable-messages/adaptive-card) to provide a lot of flexibility in release notification over the existing implementation.

**Just to mention a few:**
- Now we can tag/mention people in release notification using msteams email id.
- More control over message layout.
- Lot of future improvements with AdaptiveCard.

**Here is how it looks now:**
Screenshot 2024-01-25 at 11 29 11@2x

### CODE REVIEW

**Comment by wrzolekLukasz** [comment]
That is great! Cant wait for it to be merged!

**Comment by lucassarten** [comment]
Hello @Skitionek, any plans to merge this?

**Comment by samus42** [comment]
We'd really love this to be merged as MS Teams workflows now only really support AdaptiveCard

**Review by Skitionek — APPROVED** [review]
@minhazur-piash It is most wonderful contribution, thank you 🎉

**Pull request merged**
